include:
  - project: "nstmrt/rubygems/templates"
    ref: master
    file: "build-rubygems.yml"

tests:
  stage: test
  image: ruby:$RUBY_VERSION
  parallel:
    matrix:
      - RUBY_VERSION: ['3.1', '3.2', '3.3']
  before_script:
    - gem install bundler -v 2.5.7
    - bin/setup
  script:
    - bundle exec appraisal rspec --format RspecJunitFormatter --out test-results/rspec_$RUBY_VERSION.xml --format documentation
  artifacts:
    reports:
      junit: test-results/rspec*.xml
