services:
  ruby:
    image: ruby:${RUBY_VERSION:-3.2}
    environment:
      HISTFILE: /app/tmp/.bash_history
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_CONFIG: /app/.bundle/config
      prometheus_multiproc_dir: ./tmp
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - ${SBMT_RUBYGEMS_PATH:-..}:/app/vendor/gems:cached
      - bundler_data:/usr/local/bundle
    tmpfs:
      - /tmp

volumes:
  bundler_data:
